<?php
use \Drupal\Core\Breadcrumb\Breadcrumb;

/**
 * Implements hook_system_breadcrumb_alter().
 * Removes the post title from the breadcrumb
 */
function gig_components_system_breadcrumb_alter(\Drupal\Core\Breadcrumb\Breadcrumb &$breadcrumb, \Drupal\Core\Routing\RouteMatchInterface $route_match, array $context) {
  if ($breadcrumb) {
    $node = $route_match->getParameter('node');
    if ($node && $node->bundle() == 'post') {
      $links = $breadcrumb->getLinks();
      unset($links[count($links) - 1]);
      $breadcrumb = new Breadcrumb();
      $breadcrumb->setLinks($links);
    }
  }
}
