<?php

/**
 * @file
 * Contains media related functions.
 */

use Drupal\file\Entity\File;

/**
 * Implements hook_preprocess_views_view().
 */
function media_essentials_preprocess_views_view(&$variables) {

  $media_essentials_browser = [
    'image_browser',
    'media_browser',
  ];

  if (in_array($variables['view']->id(), $media_essentials_browser)) {
    $variables['view_array']['#attached']['library'][] = 'media_essentials/entity_browser_view';
  }
}

/**
 * Implements hook_menu_local_actions_alter().
 */
function media_essentials_menu_local_actions_alter(&$local_actions) {
  $view = \Drupal::entityTypeManager()->getStorage('view')->load('media_essentials');
  if ($view) {
    $local_actions['media.add']['appears_on'][] = 'view.media_essentials.media_page_list';
  }
}

/**
 * Implements hook_menu_links_discovered_alter().
 */
function media_essentials_menu_links_discovered_alter(&$links) {
  $view = \Drupal::entityTypeManager()->getStorage('view')->load('media_essentials');
  if ($view) {
    $links['entity.media.collection']['route_name'] = 'view.media_essentials.media_page_list';
  }
}
